b = str(input('Masukkan sekumpulan bilangan (pisahkan dengan koma)\t: ')).split(',')
terbesar = lambda b: b.split()
terkecil = lambda b: b.split()
print(f'Bilangan terbesar dari kumpulan bilangan yang di input adalah {terbesar(b)}')
print(f'Bilangan terkecil dari kumpulan bilangan yang di input adalah {terkecil(b)}')